//! `coverage nvse`: which functions of the New Vegas Script Extender
//! (xNVSE) and its plugins the loaded plugins' compiled scripts call, and
//! whether nv-rs carries them out (it doesn't run any yet). Works on one
//! plugin as well as a whole Data folder, so a mod can be checked on its
//! own. Prints Markdown.

use std::collections::{BTreeMap, BTreeSet};
use std::io::Write;

use esm::{FourCC, LoadOrder};
use script::nvse::{self, Found};

use crate::coverage_cmd::function_handled;
use crate::CliError;

/// What the plugins call, by opcode (xNVSE's and NVSE plugins' only).
#[derive(Debug, Default)]
pub struct NvseUses {
    /// Records with compiled script data (`SCDA`) looked at.
    pub scripts: usize,
    /// By opcode: calls found each way, and the records calling it
    /// (editor ID, or form ID when it has none).
    pub calls: BTreeMap<u16, (BTreeMap<Found, usize>, BTreeSet<String>)>,
    /// Conditions (`CTDA`) asking an xNVSE function, by opcode.
    pub conditions: BTreeMap<u16, usize>,
}

impl NvseUses {
    /// Every record calling any xNVSE or plugin function.
    pub fn scripts_using(&self) -> usize {
        self.calls
            .values()
            .flat_map(|(_, s)| s.iter())
            .collect::<BTreeSet<_>>()
            .len()
    }
}

pub fn nvse_uses(order: &LoadOrder) -> NvseUses {
    let (scda, ctda) = (FourCC::new(b"SCDA"), FourCC::new(b"CTDA"));
    let mut uses = NvseUses::default();
    for (p, entry) in order
        .plugins()
        .iter()
        .flat_map(|p| p.plugin.records().iter().map(move |e| (p, e)))
    {
        let Ok(subs) = p.plugin.subrecords(entry) else {
            continue;
        };
        let owner = || {
            p.plugin
                .editor_id_of(entry)
                .ok()
                .flatten()
                .unwrap_or_else(|| p.record_id(entry.header.form_id).to_string())
        };
        for sub in &subs {
            if sub.kind == scda {
                uses.scripts += 1;
                for (opcode, how) in nvse::calls(&sub.data) {
                    if opcode < nvse::FIRST_OPCODE {
                        continue;
                    }
                    let slot = uses.calls.entry(opcode).or_default();
                    *slot.0.entry(how).or_default() += 1;
                    slot.1.insert(owner());
                }
            } else if sub.kind == ctda {
                // The function's number (opcode - 0x1000) at offset 8.
                if let Some(f) = sub.data.get(8..10) {
                    let opcode = u16::from_le_bytes([f[0], f[1]]).wrapping_add(0x1000);
                    if opcode >= nvse::FIRST_OPCODE {
                        *uses.conditions.entry(opcode).or_default() += 1;
                    }
                }
            }
        }
    }
    uses
}

pub fn nvse(out: &mut impl Write, order: &LoadOrder) -> Result<(), CliError> {
    write_nvse(out, order, &nvse_uses(order))
}

fn count(map: &BTreeMap<Found, usize>, how: Found) -> usize {
    map.get(&how).copied().unwrap_or(0)
}

pub fn write_nvse(
    out: &mut impl Write,
    order: &LoadOrder,
    uses: &NvseUses,
) -> Result<(), CliError> {
    let all = &nvse::FUNCTIONS;
    let handled = |name: &str| function_handled(name);
    let used: Vec<u16> = uses
        .calls
        .keys()
        .chain(uses.conditions.keys())
        .copied()
        .collect::<BTreeSet<u16>>()
        .into_iter()
        .collect();
    let plugins: Vec<&str> = order.plugins().iter().map(|p| p.name.as_str()).collect();
    writeln!(
        out,
        "# Script extender functions: what the plugins call against nv-rs"
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "Generated by `nvinspect <plugin or Data folder> coverage nvse` from the compiled \
         scripts (`SCDA`) and conditions (`CTDA`) of: {}.",
        plugins.join(", ")
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "Opcodes from 0x{:04X} are xNVSE's functions (`script::nvse`, their names in the order \
         xNVSE registers them); from 0x{:04X} they belong to NVSE plugins (JIP LN, JohnnyGuitar \
         and others), each at the base it asks for, so only the opcode is known. Calls are \
         counted as statements, inside expressions stored the game's way, and inside \
         expressions stored xNVSE's way (found by scanning for xNVSE's call token, so those \
         counts can be off).",
        nvse::FIRST_OPCODE,
        nvse::PLUGIN_OPCODES
    )?;
    writeln!(out)?;
    writeln!(out, "## Summary")?;
    writeln!(out)?;
    let named = used.iter().filter(|&&o| nvse::name(o).is_some()).count();
    let plugin_ops = used.iter().filter(|&&o| o >= nvse::PLUGIN_OPCODES).count();
    let done = all.iter().filter(|n| handled(n)).count();
    writeln!(out, "- Compiled scripts looked at: {}.", uses.scripts)?;
    writeln!(
        out,
        "- Scripts calling the script extender: {}.",
        uses.scripts_using()
    )?;
    writeln!(
        out,
        "- xNVSE functions used: {named} of {}; NVSE plugin opcodes used: {plugin_ops}.",
        all.len()
    )?;
    writeln!(
        out,
        "- xNVSE functions nv-rs carries out: {done} of {}.",
        all.len()
    )?;
    writeln!(out)?;
    if !used.is_empty() {
        writeln!(out, "## Used")?;
        writeln!(out)?;
        writeln!(
            out,
            "| Opcode | Function | Statements | Expressions | xNVSE expressions | Conditions | Scripts | nv-rs | First scripts |"
        )?;
        writeln!(
            out,
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
        )?;
        for &opcode in &used {
            let name = nvse::name(opcode)
                .map(|n| format!("`{n}`"))
                .unwrap_or_else(|| {
                    if opcode >= nvse::PLUGIN_OPCODES {
                        "(an NVSE plugin's)".into()
                    } else {
                        "(not in xNVSE's list)".into()
                    }
                });
            let (ways, scripts) = uses.calls.get(&opcode).cloned().unwrap_or_default();
            let first: Vec<&str> = scripts.iter().take(3).map(String::as_str).collect();
            let done = nvse::name(opcode).is_some_and(handled);
            writeln!(
                out,
                "| 0x{opcode:04X} | {name} | {} | {} | {} | {} | {} | {} | {} |",
                count(&ways, Found::Statement),
                count(&ways, Found::Expression),
                count(&ways, Found::NvseExpression),
                uses.conditions.get(&opcode).copied().unwrap_or(0),
                scripts.len(),
                if done { "yes" } else { "no" },
                first.join(", ")
            )?;
        }
        writeln!(out)?;
    }
    writeln!(out, "## Every xNVSE function")?;
    writeln!(out)?;
    writeln!(out, "| Opcode | Function | Used | nv-rs |")?;
    writeln!(out, "| --- | --- | --- | --- |")?;
    for (i, name) in all.iter().enumerate() {
        let opcode = nvse::FIRST_OPCODE + i as u16;
        let n = uses
            .calls
            .get(&opcode)
            .map_or(0, |(w, _)| w.values().sum::<usize>())
            + uses.conditions.get(&opcode).copied().unwrap_or(0);
        writeln!(
            out,
            "| 0x{opcode:04X} | `{name}` | {} | {} |",
            if n == 0 { String::new() } else { n.to_string() },
            if handled(name) { "yes" } else { "no" }
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_the_script_extender_calls_of_a_plugin() {
        let case = testdata::mods::case("nvse-scripts");
        let bytes = case
            .files
            .iter()
            .find(|f| f.path.ends_with("NvseUser.esp"))
            .unwrap()
            .bytes
            .clone();
        let plugin = esm::Plugin::from_bytes(bytes).unwrap();
        let order = LoadOrder::single("NvseUser.esp", None, plugin).unwrap();
        let uses = nvse_uses(&order);
        assert_eq!(uses.scripts, 1);
        assert_eq!(uses.scripts_using(), 1);
        let ops: Vec<u16> = uses.calls.keys().copied().collect();
        assert_eq!(ops, [0x1400, 0x1401, 0x1539, 0x1567, 0x2600]);
        let mut out = Vec::new();
        assert!(write_nvse(&mut out, &order, &uses).is_ok());
        let text = String::from_utf8(out).unwrap();
        assert!(text.contains("| 0x1567 | `ar_List` | 0 | 0 | 1 | 0 | 1 | no | NvseUserScript |"));
        assert!(text.contains("| 0x2600 | (an NVSE plugin's) | 1 |"));
        assert!(text.contains("xNVSE functions used: 4 of 654; NVSE plugin opcodes used: 1."));
    }
}
