//! The game's script functions: name, short name, whether they're called
//! on a reference (`Player.GetActorValue`), and their parameters (kind
//! and whether optional), by number (the opcode minus 0x1000; dialogue
//! conditions use the same numbers). Read from the game's own function
//! table; the GECK documents the same functions.

use crate::{Param, Signature};

const fn p(kind: u8, optional: bool) -> Param {
    Param { kind, optional }
}

/// Every function, indexed by number.
pub static FUNCTIONS: [Signature; 640] = [
    Signature {
        name: "UnusedFunction0",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetDistance",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "AddItem",
        short: "",
        reference: true,
        params: &[p(50, false), p(1, false), p(1, true)],
    },
    Signature {
        name: "SetEssential",
        short: "",
        reference: false,
        params: &[p(25, false), p(1, true)],
    },
    Signature {
        name: "Rotate",
        short: "",
        reference: true,
        params: &[p(8, false), p(1, false)],
    },
    Signature {
        name: "GetLocked",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetPos",
        short: "",
        reference: true,
        params: &[p(8, false)],
    },
    Signature {
        name: "SetPos",
        short: "",
        reference: true,
        params: &[p(8, false), p(2, false)],
    },
    Signature {
        name: "GetAngle",
        short: "",
        reference: true,
        params: &[p(8, false)],
    },
    Signature {
        name: "SetAngle",
        short: "",
        reference: true,
        params: &[p(8, false), p(2, false)],
    },
    Signature {
        name: "GetStartingPos",
        short: "",
        reference: true,
        params: &[p(8, false)],
    },
    Signature {
        name: "GetStartingAngle",
        short: "",
        reference: true,
        params: &[p(8, false)],
    },
    Signature {
        name: "GetSecondsPassed",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "Activate",
        short: "",
        reference: true,
        params: &[p(4, true), p(1, true)],
    },
    Signature {
        name: "GetActorValue",
        short: "GetAV",
        reference: true,
        params: &[p(5, false)],
    },
    Signature {
        name: "SetActorValue",
        short: "SetAV",
        reference: true,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "ModActorValue",
        short: "ModAV",
        reference: true,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "SetAtStart",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetCurrentTime",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "PlayGroup",
        short: "",
        reference: true,
        params: &[p(10, false), p(1, false)],
    },
    Signature {
        name: "LoopGroup",
        short: "",
        reference: true,
        params: &[p(10, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "SkipAnim",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "StartCombat",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "StopCombat",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetScale",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsMoving",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsTurning",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetLineOfSight",
        short: "GetLOS",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "AddSpell",
        short: "",
        reference: true,
        params: &[p(7, false)],
    },
    Signature {
        name: "RemoveSpell",
        short: "",
        reference: true,
        params: &[p(7, false)],
    },
    Signature {
        name: "Cast",
        short: "",
        reference: true,
        params: &[p(11, false), p(4, false)],
    },
    Signature {
        name: "GetButtonPressed",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetInSameCell",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "Enable",
        short: "",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "Disable",
        short: "",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "GetDisabled",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "MenuMode",
        short: "",
        reference: false,
        params: &[p(1, true)],
    },
    Signature {
        name: "PlaceAtMe",
        short: "",
        reference: true,
        params: &[p(21, false), p(1, true), p(1, true), p(1, true)],
    },
    Signature {
        name: "PlaySound",
        short: "",
        reference: false,
        params: &[p(12, false), p(1, true)],
    },
    Signature {
        name: "GetDisease",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetVampire",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetClothingValue",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SameFaction",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "SameRace",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "SameSex",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "GetDetected",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "GetDead",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetItemCount",
        short: "",
        reference: true,
        params: &[p(50, false)],
    },
    Signature {
        name: "GetGold",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetSleeping",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetTalkedToPC",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "Say",
        short: "",
        reference: true,
        params: &[
            p(13, false),
            p(1, true),
            p(25, true),
            p(1, true),
            p(1, true),
        ],
    },
    Signature {
        name: "SayTo",
        short: "",
        reference: true,
        params: &[p(6, false), p(13, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "GetScriptVariable",
        short: "",
        reference: false,
        params: &[p(4, false), p(22, false)],
    },
    Signature {
        name: "StartQuest",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "StopQuest",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "GetQuestRunning",
        short: "GetQR",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "SetStage",
        short: "",
        reference: false,
        params: &[p(14, false), p(23, false)],
    },
    Signature {
        name: "GetStage",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "GetStageDone",
        short: "",
        reference: false,
        params: &[p(14, false), p(23, false)],
    },
    Signature {
        name: "GetFactionRankDifference",
        short: "",
        reference: true,
        params: &[p(17, false), p(6, false)],
    },
    Signature {
        name: "GetAlarmed",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsRaining",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetAttacked",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetIsCreature",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetLockLevel",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetShouldAttack",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "GetInCell",
        short: "",
        reference: true,
        params: &[p(9, false)],
    },
    Signature {
        name: "GetIsClass",
        short: "",
        reference: true,
        params: &[p(16, false)],
    },
    Signature {
        name: "GetIsRace",
        short: "",
        reference: true,
        params: &[p(15, false)],
    },
    Signature {
        name: "GetIsSex",
        short: "",
        reference: true,
        params: &[p(18, false)],
    },
    Signature {
        name: "GetInFaction",
        short: "",
        reference: true,
        params: &[p(17, false)],
    },
    Signature {
        name: "GetIsID",
        short: "",
        reference: true,
        params: &[p(21, false)],
    },
    Signature {
        name: "GetFactionRank",
        short: "",
        reference: true,
        params: &[p(17, false)],
    },
    Signature {
        name: "GetGlobalValue",
        short: "",
        reference: false,
        params: &[p(19, false)],
    },
    Signature {
        name: "IsSnowing",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetDisposition",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "GetRandomPercent",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "StreamMusic",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "GetQuestVariable",
        short: "",
        reference: false,
        params: &[p(14, false), p(22, false)],
    },
    Signature {
        name: "GetLevel",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetArmorRating",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "RemoveItem",
        short: "",
        reference: true,
        params: &[p(50, false), p(1, false), p(1, true)],
    },
    Signature {
        name: "ModDisposition",
        short: "",
        reference: true,
        params: &[p(6, false), p(1, false)],
    },
    Signature {
        name: "GetDeadCount",
        short: "",
        reference: false,
        params: &[p(25, false)],
    },
    Signature {
        name: "ShowMap",
        short: "",
        reference: false,
        params: &[p(24, false), p(1, true)],
    },
    Signature {
        name: "StartConversation",
        short: "",
        reference: true,
        params: &[
            p(4, false),
            p(13, true),
            p(4, true),
            p(4, true),
            p(1, true),
            p(1, true),
        ],
    },
    Signature {
        name: "Drop",
        short: "",
        reference: true,
        params: &[p(3, false), p(1, false)],
    },
    Signature {
        name: "AddTopic",
        short: "",
        reference: false,
        params: &[p(13, false)],
    },
    Signature {
        name: "ShowMessage",
        short: "",
        reference: false,
        params: &[p(49, false)],
    },
    Signature {
        name: "SetAlert",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetIsAlerted",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "Look",
        short: "",
        reference: true,
        params: &[p(4, false), p(1, true)],
    },
    Signature {
        name: "StopLook",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "EvaluatePackage",
        short: "evp",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SendAssaultAlarm",
        short: "",
        reference: false,
        params: &[p(6, true), p(17, true)],
    },
    Signature {
        name: "EnablePlayerControls",
        short: "",
        reference: false,
        params: &[
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
        ],
    },
    Signature {
        name: "DisablePlayerControls",
        short: "",
        reference: false,
        params: &[
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
        ],
    },
    Signature {
        name: "GetPlayerControlsDisabled",
        short: "",
        reference: false,
        params: &[
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
        ],
    },
    Signature {
        name: "GetHeadingAngle",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "PickIdle",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsWeaponOut",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsTorchOut",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsShieldOut",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "CreateDetectionEvent",
        short: "",
        reference: true,
        params: &[p(4, false), p(1, false), p(1, true)],
    },
    Signature {
        name: "IsActionRef",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "IsFacingUp",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetKnockedState",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetWeaponAnimType",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsWeaponSkillType",
        short: "",
        reference: true,
        params: &[p(5, false)],
    },
    Signature {
        name: "GetCurrentAIPackage",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsWaiting",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsIdlePlaying",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "CompleteQuest",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "Lock",
        short: "",
        reference: true,
        params: &[p(1, true), p(1, true)],
    },
    Signature {
        name: "UnLock",
        short: "",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "GetMinorCrimeCount",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetMajorCrimeCount",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetActorAggroRadiusViolated",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetCrimeKnown",
        short: "",
        reference: true,
        params: &[p(28, false), p(6, false), p(6, false)],
    },
    Signature {
        name: "SetEnemy",
        short: "",
        reference: false,
        params: &[p(17, false), p(17, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "SetAlly",
        short: "",
        reference: false,
        params: &[p(17, false), p(17, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "GetCrime",
        short: "",
        reference: true,
        params: &[p(6, false), p(28, true)],
    },
    Signature {
        name: "IsGreetingPlayer",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "StartMisterSandMan",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "IsGuard",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "StartCannibal",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "HasBeenEaten",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetFatiguePercentage",
        short: "GetFatigue",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetPCIsClass",
        short: "",
        reference: false,
        params: &[p(16, false)],
    },
    Signature {
        name: "GetPCIsRace",
        short: "",
        reference: false,
        params: &[p(15, false)],
    },
    Signature {
        name: "GetPCIsSex",
        short: "",
        reference: false,
        params: &[p(18, false)],
    },
    Signature {
        name: "GetPCInFaction",
        short: "",
        reference: false,
        params: &[p(17, false)],
    },
    Signature {
        name: "SameFactionAsPC",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SameRaceAsPC",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SameSexAsPC",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetIsReference",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "SetFactionRank",
        short: "",
        reference: true,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "ModFactionRank",
        short: "",
        reference: true,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "KillActor",
        short: "kill",
        reference: true,
        params: &[p(6, true), p(1, true), p(1, true)],
    },
    Signature {
        name: "ResurrectActor",
        short: "resurrect",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "IsTalking",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetWalkSpeed",
        short: "GetWalk",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetCurrentAIProcedure",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetTrespassWarningLevel",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsTrespassing",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsInMyOwnedCell",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetWindSpeed",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetCurrentWeatherPercent",
        short: "getweatherpct",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetIsCurrentWeather",
        short: "getweather",
        reference: false,
        params: &[p(33, false)],
    },
    Signature {
        name: "IsContinuingPackagePCNear",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "AddScriptPackage",
        short: "",
        reference: true,
        params: &[p(29, false)],
    },
    Signature {
        name: "RemoveScriptPackage",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "CanHaveFlames",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "HasFlames",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "AddFlames",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "RemoveFlames",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetOpenState",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "MoveToMarker",
        short: "MoveTo",
        reference: true,
        params: &[p(4, false), p(2, true), p(2, true), p(2, true)],
    },
    Signature {
        name: "GetSitting",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetFurnitureMarkerID",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetIsCurrentPackage",
        short: "",
        reference: true,
        params: &[p(29, false)],
    },
    Signature {
        name: "IsCurrentFurnitureRef",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "IsCurrentFurnitureObj",
        short: "",
        reference: true,
        params: &[p(20, false)],
    },
    Signature {
        name: "SetSize",
        short: "CSize",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "RemoveMe",
        short: "",
        reference: true,
        params: &[p(26, true)],
    },
    Signature {
        name: "DropMe",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetFactionReaction",
        short: "",
        reference: false,
        params: &[p(17, false), p(17, false)],
    },
    Signature {
        name: "SetFactionReaction",
        short: "",
        reference: false,
        params: &[p(17, false), p(17, false), p(1, false)],
    },
    Signature {
        name: "ModFactionReaction",
        short: "",
        reference: false,
        params: &[p(17, false), p(17, false), p(1, false)],
    },
    Signature {
        name: "GetDayOfWeek",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IgnoreCrime",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetTalkedToPCParam",
        short: "",
        reference: false,
        params: &[p(6, false)],
    },
    Signature {
        name: "RemoveAllItems",
        short: "",
        reference: true,
        params: &[p(26, true), p(1, true), p(1, true)],
    },
    Signature {
        name: "WakeUpPC",
        short: "",
        reference: false,
        params: &[p(1, true)],
    },
    Signature {
        name: "IsPCSleeping",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsPCAMurderer",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetCombatStyle",
        short: "setcs",
        reference: true,
        params: &[p(30, true)],
    },
    Signature {
        name: "PlaySound3D",
        short: "",
        reference: false,
        params: &[p(12, false)],
    },
    Signature {
        name: "SelectPlayerSpell",
        short: "spspell",
        reference: false,
        params: &[p(7, false)],
    },
    Signature {
        name: "GetDetectionLevel",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "IsActorDetected",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetEquipped",
        short: "",
        reference: true,
        params: &[p(50, false)],
    },
    Signature {
        name: "Wait",
        short: "",
        reference: true,
        params: &[p(29, false)],
    },
    Signature {
        name: "StopWaiting",
        short: "",
        reference: true,
        params: &[p(29, false)],
    },
    Signature {
        name: "IsSwimming",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ScriptEffectElapsedSeconds",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetCellPublicFlag",
        short: "setpublic",
        reference: false,
        params: &[p(9, false), p(1, false)],
    },
    Signature {
        name: "GetPCSleepHours",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetPCSleepHours",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetAmountSoldStolen",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ModAmountSoldStolen",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetIgnoreCrime",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetPCExpelled",
        short: "",
        reference: false,
        params: &[p(17, false)],
    },
    Signature {
        name: "SetPCExpelled",
        short: "",
        reference: false,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "GetPCFactionMurder",
        short: "",
        reference: false,
        params: &[p(17, false)],
    },
    Signature {
        name: "SetPCFactionMurder",
        short: "",
        reference: false,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "GetPCEnemyofFaction",
        short: "",
        reference: false,
        params: &[p(17, false)],
    },
    Signature {
        name: "SetPCEnemyofFaction",
        short: "",
        reference: false,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "GetPCFactionAttack",
        short: "",
        reference: false,
        params: &[p(17, false)],
    },
    Signature {
        name: "SetPCFactionAttack",
        short: "",
        reference: false,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "UnusedFunction21",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction22",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetDestroyed",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetDestroyed",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetActionRef",
        short: "getAR",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetSelf",
        short: "this",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetContainer",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetForceRun",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetForceRun",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetForceSneak",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetForceSneak",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "AdvancePCSkill",
        short: "AdvSkill",
        reference: false,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "AdvancePCLevel",
        short: "AdvLevel",
        reference: false,
        params: &[],
    },
    Signature {
        name: "HasMagicEffect",
        short: "",
        reference: true,
        params: &[p(31, false)],
    },
    Signature {
        name: "GetDefaultOpen",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetDefaultOpen",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "ShowClassMenu",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowRaceMenu",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetAnimAction",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowNameMenu",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetOpenState",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "UnusedFunction26",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsSpellTarget",
        short: "",
        reference: true,
        params: &[p(11, false)],
    },
    Signature {
        name: "GetVATSMode",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetPersuasionNumber",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetSandman",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetCannibal",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetIsClassDefault",
        short: "",
        reference: false,
        params: &[p(16, false)],
    },
    Signature {
        name: "GetClassDefaultMatch",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetInCellParam",
        short: "",
        reference: false,
        params: &[p(9, false), p(4, false)],
    },
    Signature {
        name: "SetInChargen",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetCombatTarget",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetPackageTarget",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowSpellMaking",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetVatsTargetHeight",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetGhost",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetIsGhost",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "EquipItem",
        short: "EquipObject",
        reference: true,
        params: &[p(3, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "UnequipItem",
        short: "UnEquipObject",
        reference: true,
        params: &[p(3, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "SetClass",
        short: "",
        reference: true,
        params: &[p(16, false)],
    },
    Signature {
        name: "SetUnconscious",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetUnconscious",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetRestrained",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetRestrained",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ForceFlee",
        short: "Flee",
        reference: true,
        params: &[p(9, true), p(4, true)],
    },
    Signature {
        name: "GetIsUsedItem",
        short: "",
        reference: false,
        params: &[p(53, false)],
    },
    Signature {
        name: "GetIsUsedItemType",
        short: "",
        reference: false,
        params: &[p(32, false)],
    },
    Signature {
        name: "UnusedFunction9",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction10",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction11",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction12",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction13",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction14",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetIsPlayableRace",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetOffersServicesNow",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetGameSetting",
        short: "GetGS",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "StopCombatAlarmOnActor",
        short: "SCAOnActor",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetUsedItemLevel",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetUsedItemActivate",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetWeather",
        short: "sw",
        reference: false,
        params: &[p(33, false), p(1, true)],
    },
    Signature {
        name: "ForceTakeCover",
        short: "TakeCover",
        reference: true,
        params: &[p(6, false), p(1, false)],
    },
    Signature {
        name: "ModBarterGold",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetBarterGold",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetBarterGold",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsTimePassing",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsPleasant",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsCloudy",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "TrapUpdate",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetQuestObject",
        short: "",
        reference: false,
        params: &[p(21, false), p(1, false)],
    },
    Signature {
        name: "ForceActorValue",
        short: "ForceAV",
        reference: true,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "ModPCSkill",
        short: "ModPCS",
        reference: false,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "ModPCAttribute",
        short: "ModPCA",
        reference: false,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "EnableFastTravel",
        short: "EnableFast",
        reference: false,
        params: &[p(1, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "GetArmorRatingUpperBody",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetParentRef",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "PlayBink",
        short: "",
        reference: false,
        params: &[p(0, false), p(1, true), p(1, true), p(1, true), p(1, true)],
    },
    Signature {
        name: "GetBaseActorValue",
        short: "GetBaseAV",
        reference: true,
        params: &[p(5, false)],
    },
    Signature {
        name: "IsOwner",
        short: "",
        reference: true,
        params: &[p(35, true)],
    },
    Signature {
        name: "SetOwnership",
        short: "",
        reference: true,
        params: &[p(35, true)],
    },
    Signature {
        name: "IsCellOwner",
        short: "",
        reference: true,
        params: &[p(9, false), p(35, true)],
    },
    Signature {
        name: "SetCellOwnership",
        short: "",
        reference: false,
        params: &[p(9, false), p(35, true)],
    },
    Signature {
        name: "IsHorseStolen",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetCellFullName",
        short: "",
        reference: false,
        params: &[p(9, false), p(49, false)],
    },
    Signature {
        name: "SetActorFullName",
        short: "",
        reference: true,
        params: &[p(49, false)],
    },
    Signature {
        name: "IsLeftUp",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsSneaking",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsRunning",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetFriendHit",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsInCombat",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetPackDuration",
        short: "SPDur",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "PlayMagicShaderVisuals",
        short: "PMS",
        reference: true,
        params: &[p(36, false), p(2, true)],
    },
    Signature {
        name: "PlayMagicEffectVisuals",
        short: "PME",
        reference: true,
        params: &[p(31, false), p(2, true)],
    },
    Signature {
        name: "StopMagicShaderVisuals",
        short: "SMS",
        reference: true,
        params: &[p(36, false)],
    },
    Signature {
        name: "StopMagicEffectVisuals",
        short: "SME",
        reference: true,
        params: &[p(31, false)],
    },
    Signature {
        name: "ResetInterior",
        short: "",
        reference: false,
        params: &[p(9, false)],
    },
    Signature {
        name: "IsAnimPlaying",
        short: "",
        reference: true,
        params: &[p(10, true)],
    },
    Signature {
        name: "SetActorAlpha",
        short: "SAA",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "EnableLinkedPathPoints",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "DisableLinkedPathPoints",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsInInterior",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ForceWeather",
        short: "fw",
        reference: false,
        params: &[p(33, false), p(1, true)],
    },
    Signature {
        name: "ToggleActorsAI",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsActorsAIOff",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsWaterObject",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction15",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsActorUsingATorch",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetLevel",
        short: "",
        reference: true,
        params: &[p(1, false), p(1, true), p(1, true), p(1, true)],
    },
    Signature {
        name: "ResetFallDamageTimer",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsXBox",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetInWorldspace",
        short: "",
        reference: true,
        params: &[p(27, false)],
    },
    Signature {
        name: "ModPCMiscStat",
        short: "ModPCMS",
        reference: false,
        params: &[p(41, false), p(1, false)],
    },
    Signature {
        name: "GetPCMiscStat",
        short: "GetPCMS",
        reference: false,
        params: &[p(41, false)],
    },
    Signature {
        name: "IsActorEvil",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsActorAVictim",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetTotalPersuasionNumber",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetScale",
        short: "",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "ModScale",
        short: "",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "GetIdleDoneOnce",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "KillAllActors",
        short: "killall",
        reference: false,
        params: &[p(6, true)],
    },
    Signature {
        name: "GetNoRumors",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetNoRumors",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "Dispel",
        short: "",
        reference: true,
        params: &[p(11, false)],
    },
    Signature {
        name: "WhichServiceMenu",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "TriggerHitShader",
        short: "ths",
        reference: false,
        params: &[p(2, true)],
    },
    Signature {
        name: "FunctionUnused16",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "Reset3DState",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsRidingHorse",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "DispelAllSpells",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction17",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "AddAchievement",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "DuplicateAllItems",
        short: "",
        reference: true,
        params: &[p(26, true), p(1, true)],
    },
    Signature {
        name: "IsInDangerousWater",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "EssentialDeathReload",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "SetShowQuestItems",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "DuplicateNPCStats",
        short: "",
        reference: true,
        params: &[p(6, true)],
    },
    Signature {
        name: "ResetHealth",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetIgnoreFriendlyHits",
        short: "sifh",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetIgnoreFriendlyHits",
        short: "gifh",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsPlayersLastRiddenHorse",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetActorRefraction",
        short: "sar",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "SetItemValue",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetRigidBodyMass",
        short: "",
        reference: false,
        params: &[p(2, false)],
    },
    Signature {
        name: "ShowViewerStrings",
        short: "svs",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ReleaseWeatherOverride",
        short: "rwo",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetAllReachable",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetAllVisible",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetNoAvoidance",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SendTrespassAlarm",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "SetSceneIsComplex",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "Autosave",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "StartMasterFileSeekData",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "DumpMasterFileSeekData",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsActor",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsEssential",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "PreloadMagicEffect",
        short: "",
        reference: true,
        params: &[p(31, false)],
    },
    Signature {
        name: "ShowDialogSubtitles",
        short: "",
        reference: false,
        params: &[p(1, true)],
    },
    Signature {
        name: "UnusedFunction27",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsPlayerMovingIntoNewSpace",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "UnusedFunction28",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction29",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetTimeDead",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetPlayerHasLastRiddenHorse",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetLinkedRef",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "DamageObject",
        short: "do",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "IsChild",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "UnusedFunction1",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetLastPlayerAction",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsPlayerActionActive",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetTalkingActivatorActor",
        short: "",
        reference: true,
        params: &[p(6, true)],
    },
    Signature {
        name: "IsTalkingActivatorActor",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "ShowBarterMenu",
        short: "sbm",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "IsInList",
        short: "",
        reference: true,
        params: &[p(37, false)],
    },
    Signature {
        name: "UnusedFunction18",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "AddPerk",
        short: "",
        reference: true,
        params: &[p(39, false), p(1, true)],
    },
    Signature {
        name: "RewardXP",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "ShowHackingMiniGame",
        short: "shmg",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowSurgeryMenu",
        short: "ssmg",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowRepairMenu",
        short: "srm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "FunctionUnused19",
        short: "unused",
        reference: true,
        params: &[],
    },
    Signature {
        name: "AddNote",
        short: "AN",
        reference: false,
        params: &[p(40, false)],
    },
    Signature {
        name: "RemoveNote",
        short: "RN",
        reference: false,
        params: &[p(40, false)],
    },
    Signature {
        name: "GetHasNote",
        short: "GetN",
        reference: false,
        params: &[p(40, false)],
    },
    Signature {
        name: "AddToFaction",
        short: "Addfac",
        reference: true,
        params: &[p(17, false), p(1, false)],
    },
    Signature {
        name: "RemoveFromFaction",
        short: "Removefac",
        reference: true,
        params: &[p(17, false)],
    },
    Signature {
        name: "DamageActorValue",
        short: "DamageAV",
        reference: true,
        params: &[p(5, false), p(2, false)],
    },
    Signature {
        name: "RestoreActorValue",
        short: "RestoreAV",
        reference: true,
        params: &[p(5, false), p(2, false)],
    },
    Signature {
        name: "TriggerHUDShudder",
        short: "hudsh",
        reference: false,
        params: &[p(2, true), p(2, true), p(2, true), p(2, true)],
    },
    Signature {
        name: "SetDisposition",
        short: "SetDisp",
        reference: true,
        params: &[p(6, false), p(1, false)],
    },
    Signature {
        name: "ShowComputersInterface",
        short: "sci",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetGlobalTimeMultiplier",
        short: "sgtm",
        reference: false,
        params: &[p(2, false), p(1, true)],
    },
    Signature {
        name: "GetHitLocation",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsPC1stPerson",
        short: "pc1st",
        reference: false,
        params: &[],
    },
    Signature {
        name: "PurgeCellBuffers",
        short: "pcb",
        reference: false,
        params: &[],
    },
    Signature {
        name: "PushActorAway",
        short: "",
        reference: true,
        params: &[p(4, false), p(1, false)],
    },
    Signature {
        name: "SetActorsAI",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "ClearOwnership",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetCauseofDeath",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsLimbGone",
        short: "",
        reference: true,
        params: &[p(1, false), p(1, true)],
    },
    Signature {
        name: "IsWeaponInList",
        short: "",
        reference: true,
        params: &[p(37, false)],
    },
    Signature {
        name: "PlayIdle",
        short: "",
        reference: true,
        params: &[p(0, false)],
    },
    Signature {
        name: "ApplyImageSpaceModifier",
        short: "imod",
        reference: false,
        params: &[p(42, false), p(2, true)],
    },
    Signature {
        name: "RemoveImageSpaceModifier",
        short: "rimod",
        reference: false,
        params: &[p(42, false), p(2, true)],
    },
    Signature {
        name: "HasFriendDisposition",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "FunctionUnused20",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "FriendDispositionBoost",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetCellImageSpace",
        short: "",
        reference: false,
        params: &[p(9, false), p(43, false)],
    },
    Signature {
        name: "ShowChargenMenu",
        short: "scgm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetVATSValue",
        short: "",
        reference: false,
        params: &[p(1, false), p(1, true)],
    },
    Signature {
        name: "IsKiller",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "IsKillerObject",
        short: "",
        reference: true,
        params: &[p(37, false)],
    },
    Signature {
        name: "GetFactionCombatReaction",
        short: "",
        reference: false,
        params: &[p(17, false), p(17, false)],
    },
    Signature {
        name: "UseWeapon",
        short: "",
        reference: true,
        params: &[
            p(21, false),
            p(4, false),
            p(4, false),
            p(1, false),
            p(1, true),
            p(1, true),
            p(1, true),
            p(1, true),
            p(4, true),
        ],
    },
    Signature {
        name: "EvaluateSpellConditions",
        short: "esc",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ToggleMotionBlur",
        short: "tmb",
        reference: false,
        params: &[],
    },
    Signature {
        name: "Exists",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "GetGroupMemberCount",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetGroupTargetCount",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetObjectiveCompleted",
        short: "",
        reference: false,
        params: &[p(14, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "SetObjectiveDisplayed",
        short: "",
        reference: false,
        params: &[p(14, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "GetObjectiveCompleted",
        short: "",
        reference: false,
        params: &[p(14, false), p(1, false)],
    },
    Signature {
        name: "GetObjectiveDisplayed",
        short: "",
        reference: false,
        params: &[p(14, false), p(1, false)],
    },
    Signature {
        name: "SetImageSpace",
        short: "",
        reference: false,
        params: &[p(43, true)],
    },
    Signature {
        name: "PipboyRadio",
        short: "prad",
        reference: false,
        params: &[p(0, false), p(4, true)],
    },
    Signature {
        name: "RemovePerk",
        short: "",
        reference: true,
        params: &[p(39, false), p(1, true)],
    },
    Signature {
        name: "DisableAllActors",
        short: "DisAA",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetIsFormType",
        short: "",
        reference: true,
        params: &[p(0, false)],
    },
    Signature {
        name: "GetIsVoiceType",
        short: "",
        reference: true,
        params: &[p(46, false)],
    },
    Signature {
        name: "GetPlantedExplosive",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "CompleteAllObjectives",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "IsActorTalkingThroughActivator",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetHealthPercentage",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetAudioMultithreading",
        short: "SAM",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetIsObjectType",
        short: "",
        reference: true,
        params: &[p(32, false)],
    },
    Signature {
        name: "ShowChargenMenuParams",
        short: "scgmp",
        reference: false,
        params: &[p(1, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "GetDialogueEmotion",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetDialogueEmotionValue",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ExitGame",
        short: "exit",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetIsCreatureType",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetMerchantContainer",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "RemoveMerchantContainer",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowWarning",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "EnterTrigger",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "MarkForDelete",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "AddItemHealthPercent",
        short: "",
        reference: true,
        params: &[p(3, false), p(1, false), p(2, false), p(1, true)],
    },
    Signature {
        name: "PlaceAtMeHealthPercent",
        short: "",
        reference: true,
        params: &[
            p(21, false),
            p(2, false),
            p(1, true),
            p(1, true),
            p(1, true),
        ],
    },
    Signature {
        name: "GetInZone",
        short: "",
        reference: true,
        params: &[p(47, false)],
    },
    Signature {
        name: "DisableNavMesh",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "EnableNavMesh",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "HasPerk",
        short: "",
        reference: true,
        params: &[p(39, false), p(1, true)],
    },
    Signature {
        name: "GetFactionRelation",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "IsLastIdlePlayed",
        short: "",
        reference: true,
        params: &[p(48, false)],
    },
    Signature {
        name: "SetNPCRadio",
        short: "snr",
        reference: false,
        params: &[p(1, false), p(4, false)],
    },
    Signature {
        name: "SetPlayerTeammate",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetPlayerTeammate",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetPlayerTeammateCount",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "OpenTeammateContainer",
        short: "",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "ClearFactionPlayerEnemyFlag",
        short: "",
        reference: false,
        params: &[p(17, false)],
    },
    Signature {
        name: "ClearActorsFactionsPlayerEnemyFlag",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetActorCrimePlayerEnemy",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetActorFactionPlayerEnemy",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetPlayerTagSkill",
        short: "",
        reference: false,
        params: &[p(5, false), p(1, false)],
    },
    Signature {
        name: "IsPlayerTagSkill",
        short: "",
        reference: false,
        params: &[p(5, false)],
    },
    Signature {
        name: "GetPlayerGrabbedRef",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsPlayerGrabbedRef",
        short: "",
        reference: false,
        params: &[p(4, false)],
    },
    Signature {
        name: "PlaceLeveledActorAtMe",
        short: "",
        reference: false,
        params: &[p(21, false), p(1, true), p(47, true)],
    },
    Signature {
        name: "UnusedFunction",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowLockpickMenu",
        short: "slpm",
        reference: false,
        params: &[p(1, true)],
    },
    Signature {
        name: "GetBroadcastState",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetBroadcastState",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "StartRadioConversation",
        short: "",
        reference: true,
        params: &[p(13, true)],
    },
    Signature {
        name: "GetDestructionStage",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ClearDestruction",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "CastImmediateOnSelf",
        short: "cios",
        reference: true,
        params: &[p(11, false)],
    },
    Signature {
        name: "GetIsAlignment",
        short: "",
        reference: true,
        params: &[p(51, false)],
    },
    Signature {
        name: "ResetQuest",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "SetQuestDelay",
        short: "",
        reference: false,
        params: &[p(14, false), p(2, false)],
    },
    Signature {
        name: "ForceActiveQuest",
        short: "",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "GetThreatRatio",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "MatchFaceGeometry",
        short: "",
        reference: true,
        params: &[p(6, false), p(1, false)],
    },
    Signature {
        name: "GetIsUsedItemEquipType",
        short: "",
        reference: true,
        params: &[p(52, false)],
    },
    Signature {
        name: "GetPlayerName",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "FireWeapon",
        short: "",
        reference: true,
        params: &[p(21, false)],
    },
    Signature {
        name: "ShowTutorialMenu",
        short: "",
        reference: false,
        params: &[p(49, true)],
    },
    Signature {
        name: "AgeRace",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "MatchRace",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "SetPCYoung",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SexChange",
        short: "",
        reference: false,
        params: &[p(18, true), p(1, true)],
    },
    Signature {
        name: "ShowSPECIALBookMenu",
        short: "ssbm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetConcussed",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetZoneRespawns",
        short: "",
        reference: false,
        params: &[p(47, false), p(1, false)],
    },
    Signature {
        name: "SetVATSTarget",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetMapMarkerVisible",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ResetInventory",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowSPECIALBookMenuParams",
        short: "ssbmp",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetPermanentActorValue",
        short: "GetPermAV",
        reference: true,
        params: &[p(5, false)],
    },
    Signature {
        name: "GetKillingBlowLimb",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowBarberMenu",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowPlasticSurgeonMenu",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "TriggerLODApocalypse",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetWeaponHealthPerc",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetWeaponHealthPerc",
        short: "",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "ModWeaponHealthPerc",
        short: "",
        reference: true,
        params: &[p(2, false)],
    },
    Signature {
        name: "GetRadiationLevel",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "ShowAllMapMarkers",
        short: "tmm",
        reference: false,
        params: &[p(1, false), p(1, true), p(1, true)],
    },
    Signature {
        name: "ShowChargenMenuModValues",
        short: "scgmod",
        reference: false,
        params: &[p(1, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "ResetAI",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetRumble",
        short: "",
        reference: false,
        params: &[p(2, false), p(2, false), p(2, false)],
    },
    Signature {
        name: "SetNoActivationSound",
        short: "",
        reference: false,
        params: &[p(12, false)],
    },
    Signature {
        name: "ClearNoActivationSound",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetLastHitCritical",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "PlayMusic",
        short: "",
        reference: false,
        params: &[p(54, false)],
    },
    Signature {
        name: "SetLocationSpecificLoadScreensOnly",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "ResetPipboyManager",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetPCToddler",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "IsCombatTarget",
        short: "",
        reference: true,
        params: &[p(6, false)],
    },
    Signature {
        name: "RewardKarma",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "TriggerScreenBlood",
        short: "tsb",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetVATSRightAreaFree",
        short: "",
        reference: true,
        params: &[p(4, true)],
    },
    Signature {
        name: "GetVATSLeftAreaFree",
        short: "",
        reference: true,
        params: &[p(4, true)],
    },
    Signature {
        name: "GetVATSBackAreaFree",
        short: "",
        reference: true,
        params: &[p(4, true)],
    },
    Signature {
        name: "GetVATSFrontAreaFree",
        short: "",
        reference: true,
        params: &[p(4, true)],
    },
    Signature {
        name: "GetIsLockBroken",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "IsPS3",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsWin32",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetVATSRightTargetVisible",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "GetVATSLeftTargetVisible",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "GetVATSBackTargetVisible",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "GetVATSFrontTargetVisible",
        short: "",
        reference: true,
        params: &[p(4, false)],
    },
    Signature {
        name: "AttachAshPile",
        short: "",
        reference: true,
        params: &[p(1, true)],
    },
    Signature {
        name: "SetCriticalStage",
        short: "",
        reference: true,
        params: &[p(55, false)],
    },
    Signature {
        name: "IsInCriticalStage",
        short: "",
        reference: true,
        params: &[p(55, false)],
    },
    Signature {
        name: "RemoveFromAllFactions",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetXPForNextLevel",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowLockpickMenuDebug",
        short: "slpmd",
        reference: false,
        params: &[p(1, true)],
    },
    Signature {
        name: "ForceSave",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetSPECIALPoints",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "AddSPECIALPoints",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetTagSkills",
        short: "",
        reference: false,
        params: &[p(1, false), p(1, true)],
    },
    Signature {
        name: "AddTagSkills",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "Sin",
        short: "",
        reference: false,
        params: &[p(2, false), p(1, true)],
    },
    Signature {
        name: "Cos",
        short: "",
        reference: false,
        params: &[p(2, false), p(1, true)],
    },
    Signature {
        name: "Tan",
        short: "",
        reference: false,
        params: &[p(2, false), p(1, true)],
    },
    Signature {
        name: "Sqrt",
        short: "",
        reference: false,
        params: &[p(2, false)],
    },
    Signature {
        name: "Log",
        short: "",
        reference: false,
        params: &[p(2, false), p(2, true)],
    },
    Signature {
        name: "Abs",
        short: "",
        reference: false,
        params: &[p(2, false)],
    },
    Signature {
        name: "GetQuestCompleted",
        short: "GetQC",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "ForceTerminalBack",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "PipBoyRadioOff",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "AutoDisplayObjectives",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "IsGoreDisabled",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "FadeSFX",
        short: "FSFX",
        reference: false,
        params: &[p(2, false)],
    },
    Signature {
        name: "SetMinimalUse",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetPCCanUsePowerArmor",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "ShowQuestStages",
        short: "SQS",
        reference: false,
        params: &[p(14, false)],
    },
    Signature {
        name: "GetSpellUsageNum",
        short: "",
        reference: true,
        params: &[p(11, false)],
    },
    Signature {
        name: "ForceRadioStationUpdate",
        short: "FRSU",
        reference: false,
        params: &[],
    },
    Signature {
        name: "GetActorsInHigh",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "HasLoaded3D",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "DisableAllMines",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetLastExtDoorActivated",
        short: "",
        reference: false,
        params: &[p(4, false)],
    },
    Signature {
        name: "KillQuestUpdates",
        short: "KQU",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsImageSpaceActive",
        short: "",
        reference: false,
        params: &[p(42, false)],
    },
    Signature {
        name: "AddFormToFormList",
        short: "",
        reference: false,
        params: &[p(37, false), p(61, false)],
    },
    Signature {
        name: "AddNPCToLeveledList",
        short: "",
        reference: false,
        params: &[p(58, false), p(56, false), p(1, false)],
    },
    Signature {
        name: "AddCreatureToLeveledList",
        short: "",
        reference: false,
        params: &[p(59, false), p(57, false), p(1, false)],
    },
    Signature {
        name: "AddItemToLeveledList",
        short: "",
        reference: false,
        params: &[
            p(60, false),
            p(3, false),
            p(1, false),
            p(1, false),
            p(2, false),
        ],
    },
    Signature {
        name: "RemapWaterType",
        short: "",
        reference: false,
        params: &[p(61, false), p(61, false)],
    },
    Signature {
        name: "SetReputation",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false), p(2, false)],
    },
    Signature {
        name: "AddReputation",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "RemoveReputation",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "AddReputationExact",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false), p(2, false)],
    },
    Signature {
        name: "RemoveReputationExact",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false), p(2, false)],
    },
    Signature {
        name: "GetReputation",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false)],
    },
    Signature {
        name: "GetReputationPct",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false)],
    },
    Signature {
        name: "GetReputationThreshold",
        short: "",
        reference: false,
        params: &[p(62, false), p(1, false)],
    },
    Signature {
        name: "TriggerScreenSplatter",
        short: "tssp",
        reference: false,
        params: &[p(1, false), p(2, false), p(2, false), p(2, false)],
    },
    Signature {
        name: "ClearScreenSplatter",
        short: "cssp",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetScreenSplatterTexture",
        short: "sspt",
        reference: false,
        params: &[p(0, false), p(1, false)],
    },
    Signature {
        name: "SetScreenSplatterFade",
        short: "sspf",
        reference: false,
        params: &[p(2, false), p(1, false)],
    },
    Signature {
        name: "ShowLoveTesterMenu",
        short: "sltm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowLoveTesterMenuParams",
        short: "sltmp",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetCameraFOV",
        short: "FOV",
        reference: false,
        params: &[p(2, true), p(2, true)],
    },
    Signature {
        name: "ShowTraitSelectMenu",
        short: "stsm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetSecuritronExpression",
        short: "setsecexp",
        reference: false,
        params: &[p(4, false), p(0, false), p(0, false)],
    },
    Signature {
        name: "RemoveAllTypedItems",
        short: "",
        reference: true,
        params: &[p(26, true), p(1, true), p(1, true), p(1, true), p(37, true)],
    },
    Signature {
        name: "IsHardcore",
        short: "",
        reference: true,
        params: &[],
    },
    Signature {
        name: "SetHardcore",
        short: "",
        reference: true,
        params: &[p(1, false)],
    },
    Signature {
        name: "ToggleDemigodMode",
        short: "TDM",
        reference: false,
        params: &[],
    },
    Signature {
        name: "DetonatePlacedExplosives",
        short: "dpe",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetOwnerLastTarget",
        short: "golt",
        reference: true,
        params: &[],
    },
    Signature {
        name: "MoveToMarkerWithFade",
        short: "MoveToFade",
        reference: true,
        params: &[p(4, false), p(2, true), p(2, true), p(2, true)],
    },
    Signature {
        name: "ShowRecipeMenu",
        short: "craft",
        reference: true,
        params: &[p(61, true)],
    },
    Signature {
        name: "ShowSlotMachineMenu",
        short: "sslm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowSlotMachineMenuParams",
        short: "sslmp",
        reference: false,
        params: &[p(63, false), p(1, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "ShowBlackJackMenu",
        short: "sbjm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowBlackJackMenuParams",
        short: "sbjmp",
        reference: false,
        params: &[p(63, false), p(1, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "ShowRouletteMenu",
        short: "srm",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowRouletteMenuParams",
        short: "srmp",
        reference: false,
        params: &[p(63, false), p(1, false), p(1, false), p(1, false)],
    },
    Signature {
        name: "IsCodeRedeemed",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "RedeemCode",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "GetForceHitReaction",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "ShowCaravanMenu",
        short: "crvn",
        reference: true,
        params: &[p(68, false), p(1, false), p(2, false)],
    },
    Signature {
        name: "AddCardToPlayer",
        short: "addcard",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetCasinoWinningsLevel",
        short: "",
        reference: false,
        params: &[p(63, false)],
    },
    Signature {
        name: "SetCasinoWinningsLevel",
        short: "",
        reference: false,
        params: &[p(63, false), p(1, false)],
    },
    Signature {
        name: "UnlockChallenge",
        short: "",
        reference: false,
        params: &[p(65, false)],
    },
    Signature {
        name: "ChallengeLocked",
        short: "",
        reference: false,
        params: &[p(65, false)],
    },
    Signature {
        name: "IsPlayerInRegion",
        short: "",
        reference: false,
        params: &[p(69, false)],
    },
    Signature {
        name: "SetCasinoCheatLevel",
        short: "casinocheat",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetCasinoWinningStage",
        short: "",
        reference: false,
        params: &[p(63, false)],
    },
    Signature {
        name: "PlaceAtReticle",
        short: "",
        reference: false,
        params: &[p(21, false), p(1, true), p(2, true), p(2, true)],
    },
    Signature {
        name: "PlayerInRegion",
        short: "",
        reference: false,
        params: &[p(69, false)],
    },
    Signature {
        name: "ObjectUnderReticle",
        short: "",
        reference: false,
        params: &[p(2, true), p(2, true)],
    },
    Signature {
        name: "GetChallengeCompleted",
        short: "",
        reference: false,
        params: &[p(65, false)],
    },
    Signature {
        name: "RevokeCode",
        short: "",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "ShowTraitMenu",
        short: "traitmenu",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SwapTextureOnRef",
        short: "SwapTexture",
        reference: false,
        params: &[p(4, false), p(0, false), p(0, false)],
    },
    Signature {
        name: "DisableHardcoreTracking",
        short: "babby",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsAlwaysHardcore",
        short: "behemoth",
        reference: true,
        params: &[],
    },
    Signature {
        name: "RemoveRecurringFromChallenge",
        short: "rrfc",
        reference: false,
        params: &[p(65, false)],
    },
    Signature {
        name: "ResetXP",
        short: "resetxp",
        reference: true,
        params: &[],
    },
    Signature {
        name: "GetDLCCount",
        short: "dlccount",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsDLCInstalled",
        short: "hasdlc",
        reference: false,
        params: &[p(0, false)],
    },
    Signature {
        name: "EnableLoadingMenu",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "IsLoadingMenuEnabled",
        short: "LoadMenuCheck",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IsActorRefEssential",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SetActorRefEssential",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "IsNoHumanGoreExe",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "IncrementScriptedChallenge",
        short: "",
        reference: false,
        params: &[p(65, false)],
    },
    Signature {
        name: "PersistentRefCount",
        short: "prc",
        reference: false,
        params: &[],
    },
    Signature {
        name: "AlwaysShowActorSubtitles",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "SetRadioToDialogueOnlyMode",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "ShowSleepWaitMenu",
        short: "",
        reference: false,
        params: &[p(1, false), p(1, true)],
    },
    Signature {
        name: "GetContainerInventoryCount",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "SystemSave",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "PrintTrackedCells",
        short: "",
        reference: false,
        params: &[p(1, true)],
    },
    Signature {
        name: "ClearTrackedCells",
        short: "",
        reference: false,
        params: &[],
    },
    Signature {
        name: "EnableCellTracking",
        short: "",
        reference: false,
        params: &[p(1, false)],
    },
    Signature {
        name: "GetInCharGen",
        short: "",
        reference: false,
        params: &[],
    },
];
